### ISSUE TITLE
[Bug] java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0

### ISSUE THREAD

**Issue by YanYoJun** [rvera/image-picker#139]
java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
	at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
	at java.util.ArrayList.get(ArrayList.java:308)
	at com.lzy.imagepicker.ImageDataSource.onLoadFinished(ImageDataSource.java:130)
	at com.lzy.imagepicker.ImageDataSource.onLoadFinished(ImageDataSource.java:27)
	at android.support.v4.app.LoaderManagerImpl$LoaderInfo.callOnLoadFinished(LoaderManager.java:476)
	at android.support.v4.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManager.java:444)
	at android.support.v4.content.Loader.deliverResult(Loader.java:128)
	at android.support.v4.content.CursorLoader.deliverResult(CursorLoader.java:107)
	at android.support.v4.content.CursorLoader.deliverResult(CursorLoader.java:39)
	at android.support.v4.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:257)
	at android.support.v4.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:82)
	at android.support.v4.content.ModernAsyncTask.finish(ModernAsyncTask.java:487)
	at android.support.v4.content.ModernAsyncTask$InternalHandler.handleMessage(ModernAsyncTask.java:504)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:146)
	at android.app.ActivityThread.main(ActivityThread.java:5653)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by Humni** [comment]
This is a javascript library not a java library. Not sure where you are getting this issue from

**Comment by YanYoJun** [comment]
sorry......

**Comment by antypang** [comment]
I have the same problem
